---
application_name: MJ Squared
business_name: MJ Squared, LLC
business_address: 
domain: mjsquared.elloco.dev
support_email: ellocodevteam@gmail.com
default_from_email: ellocodevteam@gmail.com
background_job_processor: solid_queue
email_provider: sendgrid
account_types: personal
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
- stripe
multitenancy:
gems:
